# Generated by Django 2.2.3 on 2020-04-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai_user', '0005_auto_20200330_0430'),
        ('rai_smartInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupofitemChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', max_length=3)),
                ('changetype', models.CharField(choices=[('1', 'Create'), ('2', 'Edit'), ('3', 'Remove')], default='0', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groupofitem',
            name='image',
            field=models.ImageField(null=True, upload_to='itemprofile'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rai_smartInventory.GroupofItem')),
                ('which_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rai_smartInventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(null=True)),
                ('items', models.ManyToManyField(to='rai_smartInventory.OrderItem')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rai_user.RAIUser')),
            ],
        ),
    ]
