# Generated by Django 2.2 on 2020-04-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0003_auto_20200413_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofitem',
            name='image',
            field=models.ImageField(null=True, upload_to='rai_smartInventory'),
        ),
    ]
