# Generated by Django 2.2.3 on 2020-04-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0004_auto_20200426_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rai_smartInventory.GroupofItem'),
        ),
    ]
