# Generated by Django 2.2 on 2020-04-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0006_auto_20200427_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_id',
            new_name='items',
        ),
    ]
