# Generated by Django 2.2.3 on 2020-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0011_auto_20200506_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='demand_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
