# Generated by Django 2.2.3 on 2020-06-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0012_order_demand_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
    ]
