# Generated by Django 2.2.3 on 2020-06-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0013_order_is_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_empty',
        ),
    ]
