# Generated by Django 2.2 on 2020-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0014_remove_order_is_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
