# Generated by Django 2.2 on 2020-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0015_orderitem_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
