# Generated by Django 2.2 on 2020-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_smartInventory', '0016_item_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
