# Generated by Django 2.2.3 on 2020-03-30 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rai_user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=30, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('path', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.TextField(default='[]')),
                ('is_show', models.BooleanField(default=False)),
                ('icon', models.ImageField(null=True, upload_to='rai_module_manager/icon')),
                ('accessibility', models.CharField(choices=[('0', 'Nobody'), ('1', 'Everyone'), ('2', 'Login Required'), ('3', 'Staff Only (Gen0)')], default='0', max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rai_user.RAIUser')),
            ],
        ),
    ]
