# Generated by Django 2.2.3 on 2020-03-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiuser',
            name='image',
        ),
    ]
