# Generated by Django 2.2.3 on 2020-03-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_user', '0002_remove_raiuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiuser',
            name='image',
            field=models.ImageField(null=True, upload_to='rai_user/image'),
        ),
    ]
