# Generated by Django 2.2.3 on 2020-03-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai_user', '0004_auto_20200330_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiuser',
            name='image',
            field=models.ImageField(default='', upload_to='rai_user/image'),
        ),
    ]
